Attribute VB_Name = "Cargar_Logo"
Sub CargaLogo()
'
' Macro4 Macro
'
' Acceso directo: CTRL+q
'
Application.ScreenUpdating = False
Sheets("TABLAS").Select
Range("A2:B2").Select
    ActiveSheet.Pictures.Insert("C:\Logo.jpg").Select
    Selection.ShapeRange.ScaleWidth 0.351825171, msoFalse, msoScaleFromTopLeft
    Selection.ShapeRange.ScaleHeight 0.3518252957, msoFalse, _
        msoScaleFromBottomRight
    Selection.ShapeRange.IncrementLeft -90
    Selection.ShapeRange.IncrementTop 170
    Selection.Copy
    Range("J7").Select
    
    Sheets("I1").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R1").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I2").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R2").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I3").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R3").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I4").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R4").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I5").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R5").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I6").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R6").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I7").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R7").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I8").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R8").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I9").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R9").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I10").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R10").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I11").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R11").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I12").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R12").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    Sheets("I13").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("R13").Select
    Range("A1").Select
    ActiveSheet.Paste
    Range("A65").Select
    ActiveSheet.Paste
    Range("A119").Select
    ActiveSheet.Paste
    Range("A183").Select
    ActiveSheet.Paste
    Range("A237").Select
    ActiveSheet.Paste
    Range("A301").Select
    ActiveSheet.Paste
    Range("A355").Select
    ActiveSheet.Paste
    Range("A461").Select
    ActiveSheet.Paste
    Range("A525").Select
    ActiveSheet.Paste
    
    
    Sheets("DS").Select
    Application.ScreenUpdating = True
    MsgBox "Proceso terminado exitosamente!"
    Range("E4").Select
End Sub

